language: elixir
elixir:
  - 1.4.4
  - 1.3.4
  - 1.2.5
  - 1.1.1
otp_release:
  - 17.4
sudo: false
before_script:
  - mix deps.get --only test
env:
  - MIX_ENV=test
script: scripts/coveralls_travis
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
